[Manager]
# A futó rendszer hardveres watchdogja marad 1 perc.
RuntimeWatchdogSec=1m
# Ha a szabályos reboot a végső leállítási fázisban beragad,
# a Raspberry Pi hardveres watchdogja 30 másodperc után resetel.
RebootWatchdogSec=30s
